name: Static Analysis (only informative)

on:
    push:
        branches:
          - master

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v1
              with:
                  php-version: 7.4
                  coverage: none

            - run: composer install --no-progress --prefer-dist
            - run: composer phpstan
              continue-on-error: true # is only informative
